### ISSUE TITLE
Touchpad pointing callbacks not working on Mac OS Sierra

### ISSUE THREAD

**Issue by Izzatbek** [INRIA/libpointing#11]
Pointing callbacks are no longer called for my embedded touchpad after the update to Mac OS Sierra, even though it appears in the list of detected pointing devices and its HID descriptor has not changed.

**Comment by Izzatbek** [comment]
I opened an issue in the [Apple Developer Forums](https://forums.developer.apple.com/message/183360). For the moment, the question is not approved by a moderator

**Comment by casiez** [comment]
Note: the code below, using hidapi,  works on El Capitan but not on Sierra: hid_read manages to read on El Capitan but not Sierra. 

```
// compile using: g++ -o trackpacklibhid trackpacklibhid.cpp -lhidapi

#include <iostream>
#include <hidapi/hidapi.h>

int main(int argc, char* arg[]) {
	hid_device *handle;

    if (hid_init() != 0) {
        std::cout << "Pb init" << std::endl;
        exit(-1);
    }

    // Adjust parameters for your trackpad
    if (!(handle = hid_open(0x05ac, 0x0263, NULL)))
    {
        handle = NULL;
        std::cout << "Pb open" << std::endl;
        exit(-1);
    }

    unsigned char d[64];
    int res;

    while (true) {
	    if ((res=hid_read(handle, d, sizeof(d))) < 0) {
	        std::cout << "Pb reading" << std::endl;
        	exit(-1);
        } else {
        	std::cout << "Received " << res << " bytes: "; 
        	for (int i=0; i<res; i++) {
        		std::cout << (int)d[i] << " ";
        	}
        	std::cout << std::endl;
        }

	}

    hid_close(handle);
}
```

**Comment by Izzatbek** [comment]
[Related](http://stackoverflow.com/questions/40954979/mouse-iohiddeviceref-not-delivering-any-input-reports-in-macos-10-12) question on stackoverflow with no answer.

**Comment by casiez** [comment]
For information the last version of **hidReportTest** does not report anything for the Touchpad while it correctly reports for an external USB mouse or the keyboard.

https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-870.31.1/tools/IOHIDReportTest.c.auto.html

**Comment by Izzatbek** [comment]
Hi @casiez. It seems like the issue was fixed with the latest Sierra update, at least on my machine (MacBook Pro Retina with Sierra 10.12.3). Could you please confirm that? Try [this example](https://gist.github.com/Izzatbek/b3c41819a1f12b02ec4d81b7a164741d) and see if you have callbacks.

**Comment by nroussel** [comment]
Fails on macOS 10.12.4 Public Beta 6 (installed this morning)

**Comment by casiez** [comment]
I've just upgraded to macOS 10.12.4 Public Beta 6 and neither consoleExample nor [this example](https://gist.github.com/Izzatbek/b3c41819a1f12b02ec4d81b7a164741d) work on my machine with the internal trackpad.

**Comment by Izzatbek** [comment]
:( I updated Xcode (to 8.2.1) and using Qt 5.8.0_1 with MacOSX10.12.sdk and consoleExample is working fine with the internal trackpad. However, I have MacBook Pro 13-inch. Not sure, if that's a reason.

**Comment by casiez** [comment]
I have the exact same versions of Xcode, Qt and macOSX sdk but it does not work on my MacBook Pro Retina 15-inch mid 2014. It's good and interesting to know it works on some computers.

**Comment by Izzatbek** [comment]
Maybe at the end 15-inch and 13-inch laptops don't have exactly the same touchpads. I run the consoleExample with `any:?debugLevel=2` and got the following output:

> HID descriptors: [ 05 01 09 02 a1 01 09 01 a1 00 05 09 19 01 29 03 15 00 25 01 85 02 95 03 75 01 81 02 95 01 75 05 81 01 05 01 09 30 09 31 15 81 25 7f 75 08 95 02 81 06 95 04 75 08 81 01 c0 c0 05 0d 09 05 a1 01 06 00 ff 09 0c 15 00 26 ff 00 75 08 95 10 85 3f 81 22 c0 06 00 ff 09 0c a1 01 06 00 ff 09 0c 15 00 26 ff 00 85 44 75 08 96 df 03 81 00 c0 ]
> +osxhid:/SPI/1000000/AppleHSSPIHIDDriver [vend:0x5ac, prod:0x273 -  Apple Internal Keyboard / Trackpad]

which does not correspond to the [descriptor](https://github.com/INRIA/libpointing/blob/0d71e80014d172f3b5b0908f7dfb3d8b3948ac64/tests/hidreportparser/hidreportparser.h#L466) in the tests (I don't have 15-inch Mac to get the descriptor now). I remember even the URI looked differently on 15-inch Mac.

**Comment by casiez** [comment]
The descriptors are indeed different. Here is mine:

HID descriptors: [ 05 01 09 02 a1 01 09 01 a1 00 05 09 19 01 29 03 15 00 25 01 85 02 95 03 75 01 81 02 95 01 75 05 81 01 05 01 09 30 09 31 15 81 25 7f 75 08 95 02 81 06 c0 c0 ]
  osxhid:/USB/14400000/AppleUSBTCButtons [vend:0x5ac, prod:0x263 - Apple Inc. Apple Internal Keyboard / Trackpad]

**Comment by casiez** [comment]
This problem exists for some trackpads with some versions of macOS. It seems the issue comes from macOS and nothing can be done on libpointing side.
