### ISSUE TITLE
autotools for linux/mac?

### ISSUE THREAD

**Issue by whot** [INRIA/libpointing#13]
Any particular reason not to use autotools for the linux build process? I just had a look at the linux/prepare script and it's a bit scary, it's not that hard to switch this over to autotools which would be a lot easier to maintain and already takes care of handling the prefix, generating tarballs etc. It should also work for OSX, including having the differnt source files for linux vs os x, etc.

Autotools is a standard on linux distros, the build process would then be simply
   autoreconfig -ivf && ./configure --prefix=/usr/ && make install

I did a quick test conversion here to be able to build easier, so I can supply the patches if wanted.

**Comment by nroussel** [comment]
Hi Peter,

The "building-and-packaging/linux/prepare" script is just used to create Debian packages.

The standard build process on Linux and OSX is "qmake && make". The various .pro files can also be opened with Qt Designer on all platforms (Linux, OSX and Windows).

I'm not against autotools, I've used them in the past. But I'm not really sure what we would gain from switching to it (especially on Windows).

Nicolas

**Comment by whot** [comment]
for the project itself, yes, you probably wouldn't get that much benefit over qmake. personally I'd like to be able to run make && make install and have the library sitting in a prefix of my choosing, but that should be possible with qmake somehow, I just never worked with it :)

but even if the prepare script is just for debian packages, you could use autotools just for that too which takes care of the manually created Makefiles and targets. you get a tarball, which is a common source for deb packages so creating the package should become more of a standard invocation of commands.
not going to push this too hard though, I'm not the maintainer here ;)

**Comment by casiez** [comment]
Can you supply the patches? This is not a priority but we will see at some point if autotools can be integrated.

**Comment by whot** [comment]
I've pushed it here but note that it's still WIP. If you want to, I can finish them off though.

https://github.com/whot/libpointing/tree/wip/autotools
