### ISSUE TITLE
PointingDevice seems to ignore cpi and hz query parameters.

### ISSUE THREAD

**Issue by dkgof** [INRIA/libpointing#2]
Hi,

Ive been looking into libpointing and it looks very cool!

I am having a problem with changing cpi and hz for a pointing device though, i tried your c++ example and when passing
"any:?cpi=1500&hz=250"

as the inputUri the pointing device getUri returns:

"winhid:?handle=0x0000000000010026&debugLevel=0&cpi=400&hz=125"

if i instead try passing:

"winhid:?handle=0x0000000000010026&debugLevel=0&cpi=1500&hz=250"

then getUri returns:

"winhid:?handle=0x0000000000010026&debugLevel=0&cpi=1500&hz=250&debugLevel=0&cpi=400&hz=125"

Also getResolution and getUpdateFrequency keeps returning 400 and 125 respectively.

This results in any transfer function where i try to enable resolution dependant scaling always gives me the same result back as it always thinks my mouse is 400cpi.

I was expecting getResolution to return 1500 and getUpdateFrequency to return 250.

If you need any extra info please ask :)

**Comment by Izzatbek** [comment]
Hi.

Indeed, cpi and hz arguments were not read properly.
Now it should work, I fixed it.

Tell me if it's not )

**Comment by Izzatbek** [comment]
I'm going to close this with 437e667b8b7f58ed8fbe1a331a3004488ec9e295. If you want to follow up with a more specific question, feel free to reopen.
