### ISSUE TITLE
Callback not being fired with input from touchpad, Windows 10, Dell XPS 15 9560

### ISSUE THREAD

**Issue by Awarua-** [INRIA/libpointing#20]
As title, may be related to #11 
ConsoleExample C++, does work for attached USB mouse, but not for the touchpad.
Unsure if this is OS, or touchpad/driver specific issue.
Note that the DELL XPS 15 does not use synaptics drivers for its touchpad, and instead uses the default Microsoft driver.

**Comment by casiez** [comment]
First, make sure your touchpad is an HID device as libpointing only handles HID devices. Second, check if your touchpad appears in the list of attached devices reported by libpointing.

**Comment by Awarua-** [comment]
@casiez 
It is listed as a PS/2 Compatible Mouse, in the device manager
But does show up when using the PointingDeviceManager class, as a winhid:/65591 [vend:0x0, prod:0x0 - unknown ACPI/PS2 device (Trackpad ?)]

**Comment by Awarua-** [comment]
I have debugged the issue, and it appears there is nothing that I can do about it.
It seems that Windows does not report the correct device for the LPARAM value passed to the rawInputProc function in the winPointingDeviceManager.cpp file, for WM_INPUT events. Instead of passing the HID of the device, too be looked up in the devMap, it passes a zero value.
However, the GIDC_ARRIVAL and GIDC_REMOVAL events do recieve a LPARAM value.

This leads me to believe it is likely a driver/hardware specific problem with Windows and has no relation to #11

**Comment by casiez** [comment]
Your device appears to be a PS/2 one, not supported by libpointing that handles only HID devices. This is not an issue of libpointing and this is not related to issue #11 that is specific to given trackpads on macOS Sierra.
