### ISSUE TITLE
resolaware query parameter seems unused

### ISSUE THREAD

**Issue by dkgof** [INRIA/libpointing#3]
In the documentation the transfer function interp has the parameter resolaware, but it seems that this parameter is not used.

I tried the following transferfunction:

"interp:./pointing-echomouse/windows/no-epp?f=4&resolaware=true"

But when i change the CPI of my mouse, (Which totally works now with the cpi parameter, :D ) then the function still returns the same result.

As an example at 2000cpi

1 mickey = 3 pixel

but if i change to 12000 CPI then

1 mickey = 3 pixels

this seems a little off as i expected that it would be equal to a different amount of pixels with a different CPI, or maybee i misunderstood how its supposed to work.

**Comment by Izzatbek** [comment]
Use `normalize` instead of `resolaware`. I'll update the docs

**Comment by dkgof** [comment]
That totally works!

Thanks alot for the speedy answer.

**Comment by Izzatbek** [comment]
Great
