### ISSUE TITLE
Linux JAR compilation

### ISSUE THREAD

**Issue by svnhub** [INRIA/libpointing#6]
I recently checked out the code and am trying to compile the Java bindings for Linux.
When running 'make all' in bindings/Java/Jar/
the process fails with 

```
../native/PointingDeviceManager.cpp: In function ‘_jobject* objectForDescriptor(JNIEnv*, const pointing::PointingDeviceDescriptor&)’:
../native/PointingDeviceManager.cpp:37:83: error: ‘const struct pointing::URI’ has no member named ‘c_str’
   jobject feature = env->NewObject(descClass, ctor, env->NewStringUTF(desc.devURI.c_str()),
                                                                                   ^
../native/PointingDeviceManager.cpp:38:59: error: ‘const struct pointing::PointingDeviceDescriptor’ has no member named ‘name’
                                    env->NewStringUTF(desc.name.c_str()), desc.vendorID, desc.productID);
                                                           ^
make: *** [PointingDeviceManager.o] Error 1
```

PointingDeviceDescriptor in pointing/input/PointingDeviceManager.h does not have a "name" and devURI is not a string.
Did you intend to write:

`jobject feature = env->NewObject(descClass, ctor, env->NewStringUTF(desc.devURI.asString().c_str()),                                    env->NewStringUTF(desc.product.c_str()), desc.vendorID, desc.productID);
`

in bindings/Java/Jar/native/PointingDeviceManager.cpp ?

**Comment by Izzatbek** [comment]
Hi, thank you for your interest.

Java bindings were not updated since I made some changes. 294de13afa0da9f88e4aa79704dcfaf602160fb0 should fix this issue.

**Comment by Izzatbek** [comment]
I will close the issue. Feel free to reopen it if it doesn't work.
