### ISSUE TITLE
Linux Building and Packaging

### ISSUE THREAD

**Issue by svnhub** [INRIA/libpointing#7]
After running 'prepare' in building-and-packaging/linux and running make in the created subdirectory I get an error saying:
`src/pointing/input/linux/linuxPointingDeviceManager.cpp:20:49: fatal error: pointing/input/linux/XInputHelper.cpp: No such file or directory`

Adding that directory to the include list in the Makefile fixes the above error but gives the following error:

```
src/pointing/input/linux/XInputHelper.o: In function `pointing::find_device_info(_XDisplay*, char const*, int)':
XInputHelper.cpp:(.text+0x0): multiple definition of `pointing::find_device_info(_XDisplay*, char const*, int)'
src/pointing/input/linux/linuxPointingDeviceManager.o:linuxPointingDeviceManager.cpp:(.text+0x0): first defined here

src/pointing/input/linux/XInputHelper.o: In function `pointing::executeCommand(_XDisplay*, _XDeviceInfo*, char const*, unsigned char)':
XInputHelper.cpp:(.text+0x1ad): multiple definition of `pointing::executeCommand(_XDisplay*, _XDeviceInfo*, char const*, unsigned char)'
src/pointing/input/linux/linuxPointingDeviceManager.o:linuxPointingDeviceManager.cpp:(.text+0x1ad): first defined here

src/pointing/input/linux/XInputHelper.o: In function `pointing::enableSynapticsTouchpad()':
XInputHelper.cpp:(.text+0x2a1): multiple definition of `pointing::enableSynapticsTouchpad()'
src/pointing/input/linux/linuxPointingDeviceManager.o:linuxPointingDeviceManager.cpp:(.text+0x2a1): first defined here
```

XInputHelper.cpp seems to be both pulled in explicitly through the includes in linuxPointingDeviceManager.cpp and through the Makefile's sources list. Did you intend to leave out XInputHelper.cpp in the sources list? - that seems to fix the issue.

**Comment by Izzatbek** [comment]
Hi, no it's not done explicitly. I will fix this issue in an hour

**Comment by Izzatbek** [comment]
4ded9b163e60aa2dc9ec47cd5dc5884a109dd9c2 should fix it.
